import 'styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react"
import NextAuthSessionProvider from 'app/SessionProvider'
import  Nav from "app/globalcomponents/NavigationBar"


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      <body >
        <NextAuthSessionProvider>
          {<Nav/>},
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}



